<?php

declare(strict_types=1);

namespace Tulia\Cms\Taxonomy\Query\Model;

use DateTime;
use Exception;
use InvalidArgumentException;
use Tulia\Cms\Metadata\MagickMetadataTrait;
use Tulia\Cms\Metadata\Metadata;
use Tulia\Cms\Metadata\MetadataTrait;

/**
 * @author Adam Banaszkiewicz
 */
class Term
{
    use MagickMetadataTrait;
    use MetadataTrait;

    protected $id;
    protected $type;
    protected $websiteId;
    protected $parentId;
    protected $level;
    protected $count;
    protected $locale;
    protected $name;
    protected $slug;
    protected $visibility;
    protected $autogeneratedLocale;

    /**
     * @var string[]
     */
    protected static $fields = [
        'id'         => 'id',
        'type'       => 'type',
        'website_id' => 'websiteId',
        'parent_id'  => 'parentId',
        'level'      => 'level',
        'count'      => 'count',
        'locale'     => 'locale',
        'name'       => 'name',
        'slug'       => 'slug',
        'visibility' => 'visibility',
        'autogenerated_locale' => 'autogeneratedLocale',
    ];

    /**
     * @param array $data
     *
     * @return Term
     *
     * @throws Exception
     */
    public static function buildFromArray(array $data): self
    {
        $node = new self();

        if (isset($data['id']) === false) {
            throw new InvalidArgumentException('Term ID must be provided.');
        }

        if (isset($data['website_id']) === false) {
            throw new InvalidArgumentException('Term website_id must be provided.');
        }

        if (isset($data['type']) === false) {
            throw new InvalidArgumentException('Term type (taxonomy type) must be provided.');
        }

        if (isset($data['locale']) === false) {
            $data['locale'] = 'en_US';
        }

        $node->setId($data['id']);
        $node->setType($data['type']);
        $node->setWebsiteId($data['website_id']);
        $node->setParentId($data['parent_id'] ?? null);
        $node->setLevel((int) ($data['level'] ?? 0));
        $node->setCount((int) ($data['count'] ?? 0));
        $node->setLocale($data['locale']);
        $node->setName($data['name'] ?? '');
        $node->setSlug($data['slug'] ?? '');
        $node->setVisibility($data['visibility'] ?? 0);
        $node->setAutogeneratedLocale($data['autogenerated_locale'] ?? false);

        $node->setMetadata(new Metadata($data['metadata'] ?? []));

        return $node;
    }

    /**
     * {@inheritdoc}
     */
    private static function setDatetime(array $data, string $key, $default = null): array
    {
        if (\array_key_exists($key, $data) === false) {
            $data[$key] = $default;
        } elseif ($data[$key] === null && $default === null) {
            // Do nothing, allow to null;
        } elseif ($data[$key] instanceof DateTime === false) {
            $data[$key] = new DateTime($data[$key]);
        }

        return $data;
    }

    /**
     * {@inheritdoc}
     */
    public function toArray(array $params = []): array
    {
        $params = array_merge([
            'skip' => [],
        ], $params);

        $result = [];

        foreach (static::$fields as $key => $property) {
            $result[$key] = $this->{$property};
        }

        foreach ($params['skip'] as $skip) {
            unset($result[$skip]);
        }

        return $result;
    }

    /**
     * {@inheritdoc}
     */
    public function hasId(): bool
    {
        return (bool) $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * {@inheritdoc}
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * {@inheritdoc}
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * {@inheritdoc}
     */
    public function getWebsiteId(): ?string
    {
        return $this->websiteId;
    }

    /**
     * {@inheritdoc}
     */
    public function setWebsiteId(?string $websiteId): void
    {
        $this->websiteId = $websiteId;
    }

    /**
     * {@inheritdoc}
     */
    public function getParentId(): ?string
    {
        return $this->parentId;
    }

    /**
     * {@inheritdoc}
     */
    public function setParentId(?string $parentId): void
    {
        $this->parentId = $parentId;
    }

    /**
     * {@inheritdoc}
     */
    public function getLevel(): int
    {
        return $this->level;
    }

    /**
     * {@inheritdoc}
     */
    public function setLevel(int $level): void
    {
        $this->level = $level;
    }

    /**
     * {@inheritdoc}
     */
    public function getCount(): int
    {
        return $this->count;
    }

    /**
     * {@inheritdoc}
     */
    public function setCount(int $count): void
    {
        $this->count = $count;
    }

    /**
     * {@inheritdoc}
     */
    public function getLocale(): ?string
    {
        return $this->locale;
    }

    /**
     * {@inheritdoc}
     */
    public function setLocale(?string $locale): void
    {
        $this->locale = $locale;
    }

    /**
     * {@inheritdoc}
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * {@inheritdoc}
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * {@inheritdoc}
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * {@inheritdoc}
     */
    public function setSlug(?string $slug): void
    {
        $this->slug = $slug;
    }

    /**
     * {@inheritdoc}
     */
    public function getVisibility(): bool
    {
        return (bool) $this->visibility;
    }

    /**
     * {@inheritdoc}
     */
    public function setVisibility($visibility): void
    {
        $this->visibility = (bool) $visibility;
    }

    /**
     * {@inheritdoc}
     */
    public function getAutogeneratedLocale(): bool
    {
        return $this->autogeneratedLocale;
    }

    /**
     * {@inheritdoc}
     */
    public function setAutogeneratedLocale($autogeneratedLocale): void
    {
        $this->autogeneratedLocale = (bool) $autogeneratedLocale;
    }
}
