services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Options\:
        resource: '../../../../*'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/*'
            - '../../../../**/Model/*'
            - '../../../../**/Exception/*'

    Tulia\Cms\Options\UserInterface\Console\Command\OptionsRegister:
        tags:
            - { name: console.command, command: 'options:register' }

    Tulia\Cms\Options\Application\Service\RegisteredOptionsCollector:
        bind:
            $providers: []
