services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Options\:
        resource: '../../../../*'

    Tulia\Cms\Options\Infrastructure\Framework\Twig\Extension\OptionsExtension:
        tags: [ twig.extension ]
