services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Security\:
        resource: '../../../../**'
        exclude: '../../../../{Infrastructure/Framework/Resources}'

    Tulia\Cms\Security\Infrastructure\Framework\Security\Authentication\Provider\UserProvider:
        tags: [ security.user_provider ]
