framework:
    twig:
        layout:
            themes:
                - bootstrap_4_layout.html.twig
        loader:
            filesystem:
                paths:
                    twig-forms:
                        path: '%kernel.system_dir%/vendor/symfony/twig-bridge/Resources/views/Form'
                    root:
                        path: '%kernel.project_dir%'
            array:
                templates:
                    theme:
                        template: "{% extends [ '@theme/layout.tpl', '@parent/layout.tpl' ] %}"
