framework:
    templating:
        paths:
            - { name: cms/homepage, path: '%kernel.project_dir%/src/cms/src/Homepage/Infrastructure/Framework/Resources/views/frontend' }
            - { name: backend/homepage, path: '%kernel.project_dir%/src/cms/src/Homepage/Infrastructure/Framework/Resources/views/backend' }
