services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Activity\:
        resource: '../../../../*'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/*'
            - '../../../../**/Model/*'
            - '../../../../**/Exception/*'

    Tulia\Cms\Activity\Infrastructure\Cms\Dashboard\Widget\ActivityWidget:
        tags: [ dashboard.widget ]
