services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Widget\:
        resource: '../../../../*'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/*'
            - '../../../../**/Model/*'
            - '../../../../**/Exception/*'

    Tulia\Cms\Widget\UserInterface\Web\Backend\Form\Extension\DefaultFieldsExtension:
        tags: [ form_extension ]

    Tulia\Cms\Widget\Infrastructure\Framework\Twig\Extension\WidgetExtension:
        bind:
            $storage: '@Tulia\Cms\Widget\Infrastructure\Widget\Storage\DatabaseStorage'

    Tulia\Cms\Widget\Application\Renderer\Renderer:
        bind:
            $storage: '@Tulia\Cms\Widget\Infrastructure\Widget\Storage\DatabaseStorage'
