services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $storage: '@Tulia\Cms\Widget\Infrastructure\Widget\Storage\DatabaseStorage'

    Tulia\Cms\Widget\:
        resource: '../../../../*'
