services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Widget\:
        resource: '../../../../**'
        exclude: '../../../../{Infrastructure/Framework/Resources}'

    Tulia\Cms\Widget\UserInterface\Web\Backend\Form\Extension\DefaultFieldsExtension:
        tags: [ form_extension ]

    Tulia\Cms\Widget\Domain\SearchAnything\SearchProvider:
        tags:
            - { name: search.provider, priority: 1000 }

    Tulia\Cms\Widget\Infrastructure\Framework\Twig\Extension\WidgetExtension:
        bind:
            $storage: '@Tulia\Cms\Widget\Infrastructure\Widget\Storage\DatabaseStorage'

    Tulia\Cms\Widget\Domain\Renderer\RendererInterface:
        class: Tulia\Cms\Widget\Domain\Renderer\Renderer
        bind:
            $storage: '@Tulia\Cms\Widget\Infrastructure\Widget\Storage\DatabaseStorage'

    Tulia\Cms\Widget\Infrastructure\Persistence\ContainerProvider\WidgetTypeContainerProvider:
        parent: Tulia\Cms\ContentBuilder\Domain\ReadModel\Service\AbstractContentTypeProvider
        bind:
            $widgets: '%cms.widgets%'
            $configuration: '%cms.content_builder.content_type_entry.config%'
