services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $storage: '@Tulia\Cms\Widget\Infrastructure\Widget\Storage\DatabaseStorage'

    Tulia\Cms\Widget\:
        resource: '../../../../*'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/*'
            - '../../../../**/Model/*'
            - '../../../../**/Exception/*'

    Tulia\Cms\Widget\UserInterface\Web\Form\Extension\DefaultFieldsExtension:
        tags: [ form_extension ]
