services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\SearchAnything\:
        resource: '../../../../**'
        exclude: '../../../../{Infrastructure/Framework/Resources}'

    Tulia\Cms\SearchAnything\Ports\SearchEngine\SearchEngineInterface:
        class: Tulia\Cms\SearchAnything\Domain\SearchEngine\SearchEngine
        bind:
            $providers: !tagged_iterator search.provider
