framework:
    translator:
        paths:
            - '%kernel.project_dir%/src/Cms/FrontendToolbar/Framework/Resources/translations'
    templating:
        paths:
            - { name: cms/frontend_toolbar, path: '%kernel.project_dir%/src/Cms/FrontendToolbar/Framework/Resources/views/frontend' }
    public_paths:
        '%kernel.project_dir%/src/Cms/FrontendToolbar/Framework/Resources/public/dist': '/core/frontend-toolbar'
