services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\FrontendToolbar\:
        resource: '../../../**'
        exclude:
        exclude: '../../../{Framework/Resources}'

    Tulia\Cms\FrontendToolbar\Links\ProviderRegistry:
        bind:
            $providers: !tagged_iterator frontend_toolbar.links.provider
