services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $environment: '%kernel.environment%'

    Tulia\Cms\Attributes\:
        resource: '../../../../../../Attributes/**'
        exclude:
            - '../../../../../../Attributes/**/Resources/**'
            - '../../../../../../Attributes/**/Model/**'
            - '../../../../../../Attributes/**/*Exception.php'
            - '../../../../../../Attributes/**/*Trait.php'

    Tulia\Cms\Attributes\Domain\ReadModel\ValueRender\ValueRendererInterface:
        class: Tulia\Cms\Attributes\Infrastructure\Framework\Twig\TwigValueRenderer
        lazy: true

    Tulia\Cms\Attributes\Domain\ReadModel\Service\AttributesValueRenderer:
        bind:
            $scopes: '%cms.attributes.finder.types%'
