services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        Tulia\Component\Importer\FileReader\FileReaderInterface:
            tags: [ importer.file_reader ]
        Tulia\Component\Importer\ObjectImporter\ObjectImporterInterface:
            tags: [ importer.object_importer ]

    Tulia\Component\Importer\:
        resource: '../../../../../../../Component/importer/src/*'
        exclude:
            - '../../../../../../Component/importer/src/**/*Exception.php'

    Tulia\Component\Importer\Schema\Schema:
        factory: [ 'Tulia\Component\Importer\Implementation\Symfony\SchemaFromContainerFactory', 'build' ]
        bind:
            $objects: '%importer.objects%'
