services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Metadata\:
        resource: '../../../../../../Metadata/**'
        exclude:
            - '../../../../../../Metadata/**/Resources/**'
            - '../../../../../../Metadata/**/Model/**'
            - '../../../../../../Metadata/**/*Exception.php'
            - '../../../../../../Metadata/**/*Trait.php'
