services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Attributes\:
        resource: '../../../../../../Attributes/**'
        exclude:
            - '../../../../../../Attributes/**/Resources/**'
            - '../../../../../../Attributes/**/Model/**'
            - '../../../../../../Attributes/**/*Exception.php'
            - '../../../../../../Attributes/**/*Trait.php'
