services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $publicDir: '%kernel.public_dir%'
            $rootDir: '%kernel.project_dir%'
            $assetsPublicPaths: '%framework.assets.public_paths%'

    Tulia\Cms\Platform\:
        resource: '../../../../../**'
        exclude: '../../../../../{Infrastructure/Framework/Resources,Domain/WriteModel,Shared}'

    Tulia\Cms\Shared\Infrastructure\Utils\DateTime\DateFormatterInterface:
        class: Tulia\Cms\Platform\Infrastructure\Utilities\DateTime\DateFormatterTranslatorAware

    Tulia\Cms\Platform\Shared\Document\DocumentInterface:
        class: Tulia\Cms\Platform\Shared\Document\Document

    Tulia\Cms\Platform\UserInterface\Console\Command\AssetsPublish:
        tags:
            - { name: console.command, command: 'assets:publish' }

    Tulia\Cms\Platform\Infrastructure\Framework\Theme\Storage\DirectoryDiscoveryStorage:
        bind:
            $extensionsDirectory: '%kernel.project_dir%/extension/theme'

    Tulia\Component\Theme\Storage\StorageInterface: '@Tulia\Cms\Platform\Infrastructure\Framework\Theme\Storage\DirectoryDiscoveryStorage'
