services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Component\Theme\:
        resource: '../../../../../../../Component/theme/src/*'
        exclude:
            - '../../../../../../Component/theme/src/src/**/*Exception.php'
            - '../../../../../../Component/theme/src/Customizer/Changeset/Changeset.php'
            - '../../../../../../Component/theme/src/Customizer/Changeset/ChangesetInterface.php'
            - '../../../../../../Component/theme/src/Customizer/Builder/Structure/Section.php'
            - '../../../../../../Component/theme/src/Customizer/Builder/Structure/Control.php'

    Tulia\Component\Theme\Customizer\Builder\BuilderInterface:
        class: Tulia\Component\Theme\Customizer\Builder\Builder

    Tulia\Component\Theme\Customizer\Builder\Rendering\Controls\RegistryInterface:
        class: Tulia\Component\Theme\Customizer\Builder\Rendering\Controls\Registry
        bind:
            $controls: !tagged_iterator theme.customizer.control

    Tulia\Component\Theme\Resolver\ResolverAggregateInterface:
        class: Tulia\Component\Theme\Resolver\ResolverAggregate
        bind:
            $resolvers: !tagged_iterator theme.resolver
