services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\EditLinks\:
        resource: '../../../**'
        exclude: '../../../{Framework/Resources}'

    Tulia\Cms\EditLinks\Service\CollectorsRegistry:
        bind:
            $collectors: !tagged_iterator edit_links.collector
