services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Activity\:
        resource: '../../../**'
        exclude:
            - '../../../Framework/Resources'
            - '../../../Model/ActivityRow.php'
