imports:
    - { resource: services/command_bus.yaml }
    - { resource: services/database.yaml }
    - { resource: services/form_builder.yaml }
    - { resource: services/hooking.yaml }
    - { resource: services/kernel.yaml }
    - { resource: services/migrations.yaml }
    - { resource: services/routing.yaml }
    - { resource: services/security.yaml }
    - { resource: services/session.yaml }
    - { resource: services/templating.yaml }
    - { resource: services/theme.yaml }
    - { resource: services/translation.yaml }
    - { resource: services/twig.yaml }
    - { resource: services/web.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    Tulia\Framework\:
        resource: '../../*'
        exclude:
            - '../../{Extension,Resources,Security}'
