framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true
    session:
        enabled: true
        handler_id: session.handler.native_file
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 86400
        use_cookies: true

    #esi: true
    #fragments: true
    php_errors:
        log: true
