framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true
    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    #esi: true
    #fragments: true
    php_errors:
        log: true
