security:
    providers:
        tulia_user_provider:
            id: Tulia\Component\Security\Core\User\UserProvider
    encoders:
        Tulia\Component\Security\Core\User\User:
            algorithm: auto
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        backend:
            pattern: ^/administrator
            anonymous: false
            provider: tulia_user_provider
            request_matcher: Tulia\Component\Security\BackendRequestMatcher
            form_login:
                login_path: backend_login
                check_path: backend_login
        main:
            anonymous: true
            lazy: true
            provider: tulia_user_provider
            guard:
                authenticators:
                    - Tulia\Component\Security\Guard\Authenticator\FrontendLoginFormAuthenticator
            logout:
                path: logout
                target: homepage
                invalidate_session: true
            form_login:
                login_path: login

    access_control:
        - { path: ^/administrator, roles: ROLE_ADMIN }
