services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\EditLinks\:
        resource: '../../../../**'
        exclude: '../../../../{Infrastructure/Framework/Resources}'

    Tulia\Cms\EditLinks\Domain\CollectorsRegistry:
        bind:
            $collectors: !tagged_iterator edit_links.collector
