services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\User\:
        resource: '../../../../*'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/*'

    Tulia\Cms\User\Infrastructure\Framework\Validator\PasswordValidatorInterface:
        class: Tulia\Cms\User\Infrastructure\Framework\Validator\PasswordValidator
        factory: Tulia\Cms\User\Infrastructure\Framework\Validator\PasswordValidatorFactory::factory

    Tulia\Cms\User\Infrastructure\Framework\Validator\UsernameValidatorInterface:
        class: Tulia\Cms\User\Infrastructure\Framework\Validator\UsernameValidator
        factory: Tulia\Cms\User\Infrastructure\Framework\Validator\UsernameValidatorFactory::factory

    Tulia\Cms\User\Infrastructure\Cms\Metadata\DefaultMetadataRegistrator:
        tags: [ metadata.registrator ]

    Tulia\Cms\User\Infrastructure\Cms\Settings\SettingsGroup:
        tags: [ settings.group ]

    Tulia\Cms\User\Application\Service\Avatar\UploaderInterface:
        class: Tulia\Cms\User\Application\Service\Avatar\Uploader
        bind:
            $publicDir: '%kernel.public_dir%'

    Tulia\Cms\User\UserInterface\Web\Form\Extension\SecurityExtension:
        bind:
            $scopes:
                - !php/const Tulia\Cms\User\UserInterface\Web\Form\ScopeEnum::BACKEND_USER
        tags: [ form_extension ]

    Tulia\Cms\User\UserInterface\Web\Form\Extension\AvatarExtension:
        bind:
            $scopes:
                - !php/const Tulia\Cms\User\UserInterface\Web\Form\ScopeEnum::BACKEND_MY_ACCOUNT
                - !php/const Tulia\Cms\User\UserInterface\Web\Form\ScopeEnum::BACKEND_USER
        tags: [ form_extension ]

    Tulia\Cms\User\UserInterface\Web\Form\UserForm\Extension\BasicsExtension:
        bind:
            $scopes:
                - !php/const Tulia\Cms\User\UserInterface\Web\Form\ScopeEnum::BACKEND_USER
        tags: [ form_extension ]

    Tulia\Cms\User\UserInterface\Web\Form\MyAccount\Extension\BasicsExtension:
        bind:
            $scopes:
                - !php/const Tulia\Cms\User\UserInterface\Web\Form\ScopeEnum::BACKEND_MY_ACCOUNT
        tags: [ form_extension ]

    Tulia\Cms\User\Infrastructure\Framework\Translator\UserLocaleResolver:
        bind:
            $translator: '@translator.default'
