services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\User\:
        resource: '../../../../*'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/*'

    Tulia\Cms\User\Infrastructure\Framework\Validator\PasswordValidatorInterface:
        class: Tulia\Cms\User\Infrastructure\Framework\Validator\PasswordValidator
        factory: Tulia\Cms\User\Infrastructure\Framework\Validator\PasswordValidatorFactory::factory

    Tulia\Cms\User\Infrastructure\Framework\Validator\UsernameValidatorInterface:
        class: Tulia\Cms\User\Infrastructure\Framework\Validator\UsernameValidator
        factory: Tulia\Cms\User\Infrastructure\Framework\Validator\UsernameValidatorFactory::factory

    Tulia\Cms\User\Infrastructure\Cms\Metadata\DefaultMetadataRegistrator:
        tags: [ metadata.registrator ]

    Tulia\Cms\User\Infrastructure\Cms\Settings\SettingsGroup:
        tags: [ settings.group ]
