services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\User\:
        resource: '../../../../**'
        exclude:
            - '../../../../Infrastructure/Framework/Resources'
            - '../../../../Domain/WriteModel/Model'
            - '../../../../Domain/WriteModel/Exception'
            - '../../../../Domain/WriteModel/Event'

    Tulia\Cms\User\Infrastructure\Framework\Validator\PasswordValidatorInterface:
        class: Tulia\Cms\User\Infrastructure\Framework\Validator\PasswordValidator
        factory: Tulia\Cms\User\Infrastructure\Framework\Validator\PasswordValidatorFactory::factory

    Tulia\Cms\User\Infrastructure\Framework\Validator\UsernameValidatorInterface:
        class: Tulia\Cms\User\Infrastructure\Framework\Validator\UsernameValidator
        factory: Tulia\Cms\User\Infrastructure\Framework\Validator\UsernameValidatorFactory::factory

    Tulia\Cms\User\Infrastructure\Cms\Settings\SettingsGroup:
        tags: [ settings.group ]

    Tulia\Cms\User\Application\Service\Avatar\UploaderInterface:
        class: Tulia\Cms\User\Application\Service\Avatar\Uploader
        bind:
            $publicDir: '%kernel.public_dir%'

    Tulia\Cms\User\UserInterface\Web\Form\Extension\AvatarExtension:
        tags: [ form_extension ]

    Tulia\Cms\User\Infrastructure\Framework\Translator\UserLocaleResolver:
        bind:
            $translator: '@translator.default'
