services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\FrontendToolbar\:
        resource: '../../../../**'
        exclude:
        exclude: '../../../../{Infrastructure/Framework/Resources}'

    Tulia\Cms\FrontendToolbar\Domain\Links\ProviderRegistry:
        bind:
            $providers: !tagged_iterator frontend_toolbar.links.provider
