cms:
    content_building:
        data_types:
            # Declare here Platform's internal field types,
            # that are used also as standalone types in standalone Forms.
            mapping:
                datetime:
                    label: Datetime
                    classname: 'Tulia\Cms\Platform\Infrastructure\Framework\Form\FormType\DateTimeType'
                    constraints: [required]
                yes_no:
                    label: Yes/No
                    classname: 'Tulia\Cms\Platform\Infrastructure\Framework\Form\FormType\YesNoType'
                    constraints: [required]
                filepicker:
                    label: Filepicker
                    # TODO move Filepicker to Filemanager module
                    classname: 'Tulia\Cms\Platform\Infrastructure\Framework\Form\FormType\FilepickerType'
                    constraints: [required]
                password:
                    label: Password
                    classname: 'Tulia\Cms\Platform\Infrastructure\Framework\Form\FormType\PasswordType'
                    constraints: [required, password]
                password_repeat:
                    label: Password repeat
                    classname: 'Tulia\Cms\Platform\Infrastructure\Framework\Form\FormType\PasswordType'
                    builder: 'Tulia\Cms\Platform\Infrastructure\Framework\Form\FormType\PasswordTypeRepeatedBuilder'
                    constraints: [required]
                    configuration:
                        referenced_field:
                            label: Source password field
                            help_text: With which password field we should copare this repeated value?
                            required: true
                locale:
                    label: Locale selector
                    classname: 'Tulia\Cms\Platform\Infrastructure\Framework\Form\FormType\LocaleType'
                    constraints: [required]
