services:
    _defaults:
        autoconfigure: true
        autowire: true

    Tulia\Cms\BodyClass\:
        resource: '../../../**'
        exclude: '../../../{Framework/Resources}'

    Tulia\Cms\BodyClass\Collector\BodyClassService:
        bind:
            $collectors: !tagged_iterator body_class.collector
