services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Website\:
        resource: '../../../../**'
        exclude: '../../../../{Infrastructure/Framework/Resources}'

    Tulia\Component\Routing\Website\WebsiteProviderInterface:
        class: Tulia\Cms\Website\Infrastructure\Framework\Routing\Website\WebsiteProvider
