services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Homepage\:
        resource: '../../../../*'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/*'
            - '../../../../**/Model/*'
            - '../../../../**/Exception/*'

    Tulia\Cms\Homepage\UserInterface\Web\Backend\BackendMenu\DefaultCmsMenuBuilder:
        tags: [ backend_menu.builder ]
