services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Component\CommandBus\Locator\LocatorInterface:
        class: Tulia\Component\CommandBus\Locator\ArrayLocator

    Tulia\Component\CommandBus\CommandBusInterface:
        class: Tulia\Component\CommandBus\CommandBus
