services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Framework\Kernel\HttpKernelInterface:
        class: Tulia\Framework\Kernel\HttpKernel
        public: true

    Psr\EventDispatcher\EventDispatcherInterface:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    Psr\Log\LoggerInterface:
        class: Symfony\Component\HttpKernel\Log\Logger

    Symfony\Contracts\EventDispatcher\EventDispatcherInterface: '@Psr\EventDispatcher\EventDispatcherInterface'

    Psr\Container\ContainerInterface: '@service_container'
    Symfony\Component\DependencyInjection\Container: '@service_container'

    Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface:
        class: Symfony\Component\DependencyInjection\ParameterBag\ContainerBag

    parameter_bag: '@Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface'

    Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface: '@Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface'
