services:
    _defaults:
        autowire: true
        autoconfigure: true

    Doctrine\Migrations\Configuration\Migration\ConfigurationLoader:
        class: Tulia\Framework\Migrations\Configuration\RuntimeConfiguration
        arguments:
            - '%kernel.project_dir%'
            - '%framework.migrations.paths%'
            - '%kernel.modules%'

    Doctrine\Migrations\Configuration\Connection\ConnectionLoader:
        class: Doctrine\Migrations\Configuration\Connection\ExistingConnection

    Doctrine\Migrations\DependencyFactory:
        class: Doctrine\Migrations\Configuration\Migration\ExistingConfiguration
        factory: Doctrine\Migrations\DependencyFactory::fromConnection

    Tulia\Framework\Migrations\Migrator: ~

    Doctrine\Migrations\Tools\Console\Command\StatusCommand:
        autowire: false
        arguments:
            - '@Doctrine\Migrations\DependencyFactory'
            - doctrine:migrations:status
        tags:
            - { name: console.command, command: doctrine:migrations:status }

    Doctrine\Migrations\Tools\Console\Command\ExecuteCommand:
        autowire: false
        arguments:
            - '@Doctrine\Migrations\DependencyFactory'
            - doctrine:migrations:execute
        tags:
            - { name: console.command, command: doctrine:migrations:execute }

    Doctrine\Migrations\Tools\Console\Command\MigrateCommand:
        autowire: false
        arguments:
            - '@Doctrine\Migrations\DependencyFactory'
            - doctrine:migrations:migrate
        tags:
            - { name: console.command, command: doctrine:migrations:migrate }

    Doctrine\Migrations\Tools\Console\Command\CurrentCommand:
        autowire: false
        arguments:
            - '@Doctrine\Migrations\DependencyFactory'
            - doctrine:migrations:current
        tags:
            - { name: console.command, command: doctrine:migrations:current }

    Doctrine\Migrations\Tools\Console\Command\DumpSchemaCommand:
        autowire: false
        arguments:
            - '@Doctrine\Migrations\DependencyFactory'
            - doctrine:migrations:dump-schema
        tags:
            - { name: console.command, command: doctrine:migrations:dump-schema }

    Doctrine\Migrations\Tools\Console\Command\GenerateCommand:
        autowire: false
        arguments:
            - '@Doctrine\Migrations\DependencyFactory'
            - doctrine:migrations:generate
        tags:
            - { name: console.command, command: doctrine:migrations:generate }

    Doctrine\Migrations\Tools\Console\Command\LatestCommand:
        autowire: false
        arguments:
            - '@Doctrine\Migrations\DependencyFactory'
            - doctrine:migrations:latest
        tags:
            - { name: console.command, command: doctrine:migrations:latest }

    Doctrine\Migrations\Tools\Console\Command\ListCommand:
        autowire: false
        arguments:
            - '@Doctrine\Migrations\DependencyFactory'
            - doctrine:migrations:list
        tags:
            - { name: console.command, command: doctrine:migrations:list }

    Doctrine\Migrations\Tools\Console\Command\RollupCommand:
        autowire: false
        arguments:
            - '@Doctrine\Migrations\DependencyFactory'
            - doctrine:migrations:rollup
        tags:
            - { name: console.command, command: doctrine:migrations:rollup }

    Doctrine\Migrations\Tools\Console\Command\SyncMetadataCommand:
        autowire: false
        arguments:
            - '@Doctrine\Migrations\DependencyFactory'
            - doctrine:migrations:sync-metadata-storage
        tags:
            - { name: console.command, command: doctrine:migrations:sync-metadata-storage }

    Doctrine\Migrations\Tools\Console\Command\UpToDateCommand:
        autowire: false
        arguments:
            - '@Doctrine\Migrations\DependencyFactory'
            - doctrine:migrations:up-to-date
        tags:
            - { name: console.command, command: doctrine:migrations:up-to-date }

    Doctrine\Migrations\Tools\Console\Command\VersionCommand:
        autowire: false
        arguments:
            - '@Doctrine\Migrations\DependencyFactory'
            - doctrine:migrations:version
        tags:
            - { name: console.command, command: doctrine:migrations:version }
