services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Component\Security\Csrf\TokenStorage\TokenStorageInterface:
        class: Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage

    Symfony\Component\Security\Csrf\CsrfTokenManagerInterface:
        class: Symfony\Component\Security\Csrf\CsrfTokenManager
        bind:
            $generator: null

    Tulia\Framework\Twig\Extension\CsrfExtension:
        tags: [ twig.extension ]

    Tulia\Framework\Security\Http\Csrf\EventListener\ControllerRequestTokenValidator:
        tags: [ kernel.event_subscriber ]
