services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Component\Translation\Translator:
        factory: Tulia\Framework\Translation\Factory::create
        bind:
            $directories: '%framework.translation.directory_list%'
            $debug: '%kernel.debug%'
            $cacheDir: '%kernel.cache_dir%'

    #todo make translator debuggable in Compiler Pass
    #Symfony\Contracts\Translation\TranslatorInterface: '@Symfony\Component\Translation\Translator'
    Symfony\Contracts\Translation\TranslatorInterface: '@Symfony\Component\Translation\DataCollectorTranslator'

    Tulia\Framework\Twig\Extension\TranslatorExtension:
        tags: [ twig.extension ]

    Tulia\Framework\Translation\LocaleResolver:
        tags: [ event_subscriber ]

    Symfony\Component\Translation\DataCollectorTranslator:
        bind:
            $translator: '@Symfony\Component\Translation\Translator'

    Symfony\Component\Translation\DataCollector\TranslationDataCollector:
        tags: [ profiler.data_collector ]
