parameters:
    # List of scopes, where ContentRenderer listener will work. Allows to bind Node's
    # content rendering in many more scopes than default ones, even for custom created
    # by extensions.
    cms.node.finder.content_renderer.scopes:
        - !php/const Tulia\Cms\Node\Domain\ReadModel\Finder\NodeFinderScopeEnum::SINGLE
        - !php/const Tulia\Cms\Node\Domain\ReadModel\Finder\NodeFinderScopeEnum::ROUTING_MATCHER

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Node\:
        resource: '../../../../**'
        exclude: '../../../../{Infrastructure/Framework/Resources}'

    Tulia\Cms\Node\Domain\NodeFlag\NodeFlagRegistryInterface:
        class: Tulia\Cms\Node\Domain\NodeFlag\NodeFlagRegistry
        bind:
            $providers: !tagged_iterator node.flag_provider

    Tulia\Cms\Node\Infrastructure\Framework\Routing\SymfonyRouter:
        tags: [ routing_chain.router ]

    Tulia\Cms\Node\Domain\Menu\IdentityProvider:
        tags: [ menu.identity_provider ]

    Tulia\Cms\Node\UserInterface\Web\Backend\Settings\SettingsFactory:
        tags: [ settings.group_factory ]

    Tulia\Cms\Node\Domain\SearchAnything\SearchProvider:
        tags:
            - { name: search.provider, priority: 1000 }

    Tulia\Cms\Node\Application\EventListener\RegisterContentRenderer:
        bind:
            $scopes: '%cms.node.finder.content_renderer.scopes%'

    Tulia\Cms\Node\Domain\ReadModel\NodeContent\NodeContentFactoryInterface:
        class: Tulia\Cms\Node\Infrastructure\Domain\ReadModel\NodeContent\TwigRenderingNodeContentFactory
        bind:
            $environment: '%kernel.environment%'

    Tulia\Cms\Node\Domain\Filemanager\ImageSize\DefaultSizesImagesSizeProvider:
        tags: [ filemanager.image_size.provider ]
