services:
    Requtize\Assetter\AssetterInterface:
        class: Requtize\Assetter\Assetter
        factory: Tulia\Component\Templating\Assetter\Factory::factory
        bind:
            $assets: '%framework.assetter.assets%'
            $config:
                global_revision: !php/const Tulia\Cms\Platform\Version::VERSION
