services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Component\FormBuilder\:
        resource: '../../../../../../Component/form-builder/src/*'
        exclude:
            - '../../../../../Component/form-builder/src/src/**/*Exception.php'

    Tulia\Component\FormBuilder\RegistryInterface:
        class: Tulia\Component\FormBuilder\Registry
        bind:
            $extensions: !tagged_iterator form_extension
            $extensionsAggregate: !tagged_iterator form_extension_aggregate

    Tulia\Component\FormBuilder\Builder\BuilderInterface:
        class: Tulia\Component\FormBuilder\Builder\Builder
        bind:
            $builders: !tagged_iterator form_extension.group_builder

    Tulia\Component\FormBuilder\Extension\FormRestExtension:
        tags: [ form_extension ]

    #Tulia\Component\FormBuilder\Builder\BootstrapAccordionGroupBuilder:
    #    tags: [ form_extension.group_builder ]

    #Tulia\Component\FormBuilder\Builder\BootstrapTabsGroupBuilder:
    #    tags: [ form_extension.group_builder ]

    Tulia\Component\FormBuilder\Builder\BootstrapAccordionGroupBuilder:
        tags: [ form_extension.group_builder ]
        arguments:
            - sidebar
            - >
                {%% import '@backend/_macros/form/bootstrap/badge.tpl' as badge %%}
                <div class="accordion-section">
                    <div class="accordion-section-button{sectionActiveTab}" data-toggle="collapse" data-target="#form-collapse-{sectionId}">
                        {sectionFields}
                        {{ '{sectionLabel}'|trans({}, '{sectionTranslationDomain}') }}
                        {{ badge.errors_count(form, fields|default([])) }}
                    </div>
                    <div id="form-collapse-{sectionId}" class="collapse{sectionActiveContent}">
                        <div class="accordion-section-body">
                            {sectionView}
                        </div>
                    </div>
                </div>

    Tulia\Component\FormBuilder\Builder\BootstrapTabsGroupBuilder:
        tags: [ form_extension.group_builder ]
        arguments:
            - default
            - >
                {%% import '@backend/_macros/form/bootstrap/badge.tpl' as badge %%}
                <li class="nav-item">
                    <a class="nav-link{sectionActive}" data-toggle="tab" href="#tab-{sectionId}">
                        {sectionFields}
                        {{ '{sectionLabel}'|trans({}, '{sectionTranslationDomain}') }}
                        {{ badge.errors_count(form, fields|default([])) }}
                    </a>
                </li>
