services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Component\Routing\:
        resource: '../../../../../../Component/routing/src/*'
        exclude:
            - '../../../../../Component/routing/src/**/*Exception.php'
            - '../../../../../Component/routing/src/SymfonyRouterDecorator.php'

    Tulia\Component\Routing\SymfonyRouterDecorator:
        decorates: router.default
        autowire: false
        autoconfigure: false
        arguments:
            - '@.inner'
            - '@Tulia\Component\Routing\ChainRouterInterface'

    Tulia\Component\Routing\Website\RegistryInterface:
        factory: Tulia\Component\Routing\Website\GenericWebsiteRegistryFactory::factory
