services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Component\Security\:
        resource: '../../../../../../Component/security/src/*'
        exclude:
            - '../../../../../../Component/security/src/Core/User/User.php'
