services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Component\Templating\:
        resource: '../../../../../../Component/templating/src/*'

    Tulia\Component\Templating\Twig\Loader\AdvancedFilesystemLoader:
        bind:
            $paths: '%framework.templating.paths%'

    Tulia\Component\Templating\Twig\Loader\LazyArrayLoader:
        bind:
            $templates: '%framework.twig.loader.array.templates%'

    Tulia\Component\Templating\ViewFilter\FilterInterface:
        class: Tulia\Component\Templating\ViewFilter\DelegatingFilter

    Tulia\Component\Templating\ViewFilter\ViewNamespaceOverwriteFilter:
        tags: [ templating.view_filter ]

    Tulia\Component\Templating\Config:
        arguments:
            - { namespace_overwrite: '%framework.templating.namespace_overwrite%' }

    Twig\Extension\StringLoaderExtension: ~
