services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Component\Widget\:
        resource: '../../../../../../Component/widget/src/*'
        exclude:
            - '../../../../../Component/widget/src/src/**/*Exception.php'

    Tulia\Component\Widget\Registry\WidgetRegistryInterface:
        class: Tulia\Component\Widget\Registry\WidgetRegistry
        bind:
            $widgets: !tagged_iterator widget
