framework:
    translator:
        paths:
            - '%kernel.project_dir%/src/Cms/ContentBuilder/Infrastructure/Framework/Resources/translations'
    templating:
        paths:
            - { name: backend/contentbuilder, path: '%kernel.project_dir%/src/Cms/ContentBuilder/Infrastructure/Framework/Resources/views/backend' }

cms:
    content_building:
        node_types:
            page:
                controller: 'Tulia\Cms\Node\UserInterface\Web\Frontend\Controller\Node::show'
                is_routable: true
                is_hierarchical: true
                routable_taxonomy_field: category
                translation_domain: page
                layout: default
                fields:
                    title:
                        type: text
                        is_title: true
                    introduction:
                        label: false
                        type: textarea
                    slug:
                        type: text
                        is_slug: true
                    content:
                        type: wysiwyg
                    #category:
                    #    label: category
                    #    type: taxonomy
                        #relation:
                        #    type:

#        taxonomy_types:
#            category:
#                translation_domain: category
#
        layout_types:
            default:
                label: defaultLayout
                sections:
                    lead:
                        groups:
                            main:
                                label: main
                                fields: [title, slug]
                    main:
                        groups:
                            introduction:
                                label: introduction
                                fields: [introduction]
                            content:
                                label: content
                                fields: [content]
                    sidebar:
                        groups:
                            introduction:
                                active: true
                                label: introduction
                                fields: [introduction]

        field_types:
            mapping:
                text:
                    classname: 'Symfony\Component\Form\Extension\Core\Type\TextType'
