framework:
    translator:
        paths:
            - '%kernel.project_dir%/src/Cms/ContentBuilder/Infrastructure/Framework/Resources/translations'
    public_paths:
        '%kernel.project_dir%/src/Cms/ContentBuilder/Infrastructure/Framework/Resources/public/layout_builder/dist': '/core/content-builder-layout-builder'
    templating:
        paths:
            - { name: backend/content_builder, path: '%kernel.project_dir%/src/Cms/ContentBuilder/Infrastructure/Framework/Resources/views/backend' }
    assetter:
        assets:
            content_builder.layout_builder.routable_content_type:
                scripts: [ '/assets/core/content-builder-layout-builder/js/build.js' ]
                styles: [ '/assets/core/content-builder-layout-builder/css/styles.min.css' ]
                require: [ vue, lodash ]

monolog:
    channels: ['contentBuilder']

cms:
    content_building:
        data_types:
            mapping:
                text:
                    label: Textline
                    classname: 'Symfony\Component\Form\Extension\Core\Type\TextType'
                    constraints: [required, pattern, length]
                textarea:
                    label: Textarea
                    classname: 'Symfony\Component\Form\Extension\Core\Type\TextareaType'
                    constraints: [required, pattern, length]
                select:
                    label: Select
                    classname: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
                    builder: 'Tulia\Cms\ContentBuilder\UserInterface\Web\Shared\Form\FormType\ChoiceTypeBuilder'
                    constraints: [required]
                    configuration:
                        choices:
                            required: true
                            type: textarea
                            label: Enter the available choices for this select
                            help_text: "Every entry in new line. Format: \"value: Option label\""
                            placeholder: |
                                value-1: Option label 1
                                value-2: Option label 2
                        multiple:
                            required: true
                            type: yes_no
                            label: Allows select multiple values at once
                        placeholder:
                            label: Placeholder text
                            help_text: Shows when no value selected.
                repeatable:
                    label: Repeatable
                    classname: 'Tulia\Cms\ContentBuilder\UserInterface\Web\Shared\Form\FormType\RepeatableGroupType'

        constraint_types:
            mapping:
                required:
                    classname: 'Symfony\Component\Validator\Constraints\NotBlank'
                    label: Required
                    help_text: Makes this field required.
                pattern:
                    classname: 'Symfony\Component\Validator\Constraints\Regex'
                    label: Text pattern
                    help_text: Regular expression pattern.
                    modificators:
                        pattern:
                            type: string
                            label: Regular expression pattern
                length:
                    classname: 'Symfony\Component\Validator\Constraints\Length'
                    label: Text length
                    help_text: Min and max text length.
                    modificators:
                        min:
                            type: integer
                            label: Minimal characters length
                            value: null
                        max:
                            type: integer
                            label: Maximal characters length
                            value: null
