framework:
    translator:
        paths:
            - '%kernel.project_dir%/src/Cms/ContentBuilder/Infrastructure/Framework/Resources/translations'
    templating:
        paths:
            - { name: backend/content_builder, path: '%kernel.project_dir%/src/Cms/ContentBuilder/Infrastructure/Framework/Resources/views/backend' }
    assetter:
        assets:
            content_builder.layout_builder:
                scripts: [ '/assets/core/content-builder-layout-builder/js/build.js' ]
                styles: [ '/assets/core/content-builder-layout-builder/css/styles.min.css' ]
                require: [ vue, lodash ]

monolog:
    channels: ['contentBuilder']

cms:
    content_building:
        node_type:
            default_controller: 'Tulia\Cms\Node\UserInterface\Web\Frontend\Controller\Node::show'
            mapping:
                page:
                    name: Page
                    icon: 'fas fa-file-powerpoint'
                    is_routable: true
                    is_hierarchical: true
                    routable_taxonomy_field: category
                    layout: node_default
                    fields:
                        introduction:
                            type: textarea
                            is_multilingual: true
                            name: ~
                            constraints:
                                length:
                                    modificators:
                                        - { modificator: max, value: 255 }
                        content:
                            type: wysiwyg
                            is_multilingual: true
                        category:
                            name: category
                            type: taxonomy
                            taxonomy: category
                        tags:
                            name: tags
                            type: taxonomy
                            taxonomy: tag
                        thumbnail:
                            name: thumbnail
                            type: filepicker

        taxonomy_type:
            default_controller: 'Tulia\Cms\Taxonomy\UserInterface\Web\Frontend\Controller\Term::show'
            mapping:
                category:
                    name: Category
                    routing_strategy: simple
                    is_routable: true
                    is_hierarchical: true
                    layout: taxonomy_default
                tag:
                    name: Tag
                    routing_strategy: simple
                    is_routable: true
                    is_hierarchical: false
                    layout: taxonomy_default

        layout_types:
            default_builder: 'Tulia\Cms\ContentBuilder\Infrastructure\Presentation\TwigLayoutTypeBuilder'
            mapping:
                node_default:
                    name: defaultLayout
                    sections:
                        main:
                            groups:
                                introduction:
                                    name: introduction
                                    fields: [introduction]
                                content:
                                    active: true
                                    interior: full-width
                                    name: content
                                    fields: [content]
                        sidebar:
                            groups:
                                category:
                                    name: taxonomy
                                    fields: [category, tags]
                                thumbnail:
                                    name: thumbnail
                                    fields: [thumbnail]
                taxonomy_default:
                    name: defaultLayout
                    sections:
                        main:
                            groups: ~
                        sidebar:
                            groups: ~

        data_types:
            mapping:
                text:
                    label: Textline
                    classname: 'Symfony\Component\Form\Extension\Core\Type\TextType'
                    constraints: [required, pattern, length]
                textarea:
                    label: Textarea
                    classname: 'Symfony\Component\Form\Extension\Core\Type\TextareaType'
                    constraints: [required, pattern, length]
                select:
                    label: Select
                    classname: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
                    builder: 'Tulia\Cms\ContentBuilder\UserInterface\Web\Shared\Form\FormType\ChoiceTypeBuilder'
                    constraints: [required]
                    configuration:
                        choices:
                            required: true
                            type: textarea
                            label: Enter the available choices for this select
                            help_text: "Every entry in new line. Format: \"value: Option label\""
                            placeholder: |
                                value-1: Option label 1
                                value-2: Option label 2
                        multiple:
                            required: true
                            type: yes_no
                            label: Allows select multiple values at once
                        placeholder:
                            label: Placeholder text
                            help_text: Shows when no value selected.

        constraint_types:
            mapping:
                required:
                    classname: 'Symfony\Component\Validator\Constraints\NotBlank'
                    label: Required
                    help_text: Makes this field required.
                pattern:
                    classname: 'Symfony\Component\Validator\Constraints\Regex'
                    label: Text pattern
                    help_text: Regular expression pattern.
                    modificators:
                        pattern:
                            type: string
                            label: Regular expression pattern
                length:
                    classname: 'Symfony\Component\Validator\Constraints\Length'
                    label: Text length
                    help_text: Min and max text length.
                    modificators:
                        min:
                            type: integer
                            label: Minimal characters length
                            value: null
                        max:
                            type: integer
                            label: Maximal characters length
                            value: null
