framework:
    translator:
        paths:
            - '%kernel.project_dir%/src/Cms/ContentBuilder/Infrastructure/Framework/Resources/translations'
    templating:
        paths:
            - { name: backend/contentbuilder, path: '%kernel.project_dir%/src/Cms/ContentBuilder/Infrastructure/Framework/Resources/views/backend' }

monolog:
    channels: ['contentBuilder']

cms:
    content_building:
        node_types:
            page:
                controller: 'Tulia\Cms\Node\UserInterface\Web\Frontend\Controller\Node::show'
                is_routable: true
                is_hierarchical: true
                routable_taxonomy_field: category
                translation_domain: page
                layout: default
                fields:
                    title:
                        is_title: true
                        type: text
                        label: title
                        multilingual: true
                        constraints:
                            - { name: required }
                    slug:
                        label: slug
                        type: text
                        is_slug: true
                        multilingual: true
                        constraints:
                            - { name: required }
                    introduction:
                        type: textarea
                        multilingual: true
                        label: ~
                    content:
                        type: wysiwyg
                        multilingual: true

                    ##########
                    #title:
                    #    name: Title
                    #    help: Title of tne entry
                    #    datatype: text
                    #    multiple: false
                    #    multilingual: true
                    #    appearance: textline
                    #    is_title: true
                    #    validation:
                    #        - { type: required }
                    #slug:
                    #    name: Title
                    #    help: Title of tne entry
                    #    datatype: text
                    #    multiple: false
                    #    multilingual: true
                    #    appearance: textline
                    #    is_slug: true
                    #    validation:
                    #        - { type: required }
                    #        - { type: unique, globally: true }
                    #content:
                    #    name: Content
                    #    help: This is main content of the node
                    #    datatype: text
                    #    multiple: false
                    #    multilingual: true
                    #    appearance: tulia-editor
                    #introduction:
                    #    name: Introduction
                    #    help: Introductions of the node's content
                    #    datatype: text
                    #    multiple: false
                    #    multilingual: true
                    #    appearance: text-block

                    #category:
                    #    label: category
                    #    type: taxonomy
                        #relation:
                        #    type:

#        taxonomy_types:
#            category:
#                translation_domain: category
#
        layout_types:
            default:
                label: defaultLayout
                sections:
                    lead:
                        groups:
                            main:
                                label: main
                                fields: [title, slug]
                    main:
                        groups:
                            introduction:
                                label: introduction
                                fields: [introduction]
                            content:
                                active: true
                                interior: full-width
                                label: content
                                fields: [content]
                    sidebar:
                        groups:
                            introduction:
                                active: true
                                label: introduction
                                fields: []

        data_types:
            mapping:
                text:
                    label: Textline
                    classname: 'Symfony\Component\Form\Extension\Core\Type\TextType'
                textarea:
                    label: Textarea
                    classname: 'Symfony\Component\Form\Extension\Core\Type\TextareaType'
                select:
                    label: Select
                    classname: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'

        constraints_types:
            mapping:
                required:
                    classname: 'Symfony\Component\Validator\Constraints\NotBlank'
