services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tulia\Cms\ContentBuilder\:
        resource: '../../../../**'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/**'
            - '../../../../Domain/**/Model/**'
            - '../../../../Domain/**/Exception/**'
            - '../../../../UserInterface/LayoutType/Model/**'

    Tulia\Cms\ContentBuilder\Domain\ReadModel\Service\AbstractContentTypeProvider:
        abstract: true
        calls:
            - setArrayToReadModelTransformer: [ '@Tulia\Cms\ContentBuilder\Domain\ReadModel\Service\ArrayToReadModelTransformer' ]

    Tulia\Cms\ContentBuilder\Infrastructure\Persistence\ContentProvider\ContentTypeDatabaseProvider:
        parent: Tulia\Cms\ContentBuilder\Domain\ReadModel\Service\AbstractContentTypeProvider

    Tulia\Cms\ContentBuilder\Infrastructure\Persistence\ContentProvider\ContentTypeContainerProvider:
        parent: Tulia\Cms\ContentBuilder\Domain\ReadModel\Service\AbstractContentTypeProvider
        arguments:
            $configuration: '%cms.content_builder.content_type_entry.config%'

    Tulia\Cms\ContentBuilder\UserInterface\Web\Backend\Form\ContentType\FormHandler:
        shared: false

    Tulia\Cms\ContentBuilder\Domain\WriteModel\ContentType\Service\Configuration:
        arguments:
            $configuration: '%cms.content_builder.content_type.config%'
