services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tulia\Cms\ContentBuilder\:
        resource: '../../../../**'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/**'
            - '../../../../Domain/LayoutType/Model/**'
            - '../../../../Domain/ContentType/Model/**'
            - '../../../../Domain/ContentType/Exception/**'
            - '../../../../UserInterface/LayoutType/Model/**'

    Tulia\Cms\ContentBuilder\Domain\ContentType\Service\AbstractContentTypeProvider:
        abstract: true
        calls:
            - setFieldTypeMappingRegistry: [ '@Tulia\Cms\ContentBuilder\UserInterface\LayoutType\Service\FieldTypeMappingRegistry' ]
            - setConfiguration: [ '@Tulia\Cms\ContentBuilder\Domain\ContentType\Service\Configuration' ]

    Tulia\Cms\ContentBuilder\Infrastructure\Persistence\ContentProvider\ContentTypeDatabaseProvider:
        parent: Tulia\Cms\ContentBuilder\Domain\ContentType\Service\AbstractContentTypeProvider

    Tulia\Cms\ContentBuilder\UserInterface\Web\Backend\Form\ContentType\FormHandler:
        shared: false

    Tulia\Cms\ContentBuilder\Domain\ContentType\Service\Configuration:
        arguments:
            $configuration: '%cms.content_builder.content_type.config%'
