services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Menu\:
        resource: '../../../../*'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/*'
            - '../../../../**/Model/*'
            - '../../../../**/Exception/*'

    Tulia\Cms\Menu\Infrastructure\Framework\Twig\Extension\MenuExtension:
        tags: [ twig.extension ]

    Tulia\Cms\Menu\UserInterface\Web\BackendMenu\MenuMenuBuilder:
        tags: [ backend_menu.builder ]

    Tulia\Cms\Menu\Infrastructure\Cms\SearchAnything\SearchProvider:
        tags:
            - { name: search.provider, priority: 500 }

    Tulia\Cms\Menu\Infrastructure\Framework\Form\FormType\MenuItemChoiceType:
        tags: [ form.type ]

    Tulia\Cms\Menu\UserInterface\Web\Form\MenuItemForm:
        tags: [ form.type ]

    Tulia\Cms\Menu\Domain\Builder\Identity\RegistryInterface:
        class: Tulia\Cms\Menu\Domain\Builder\Identity\Registry
        bind:
            $providers: !tagged_iterator menu.identity_provider

    Tulia\Cms\Menu\Domain\Builder\Type\RegistryInterface:
        class: Tulia\Cms\Menu\Domain\Builder\Type\Registry
        bind:
            $registrators: !tagged_iterator menu.builder.type_registrator

    Tulia\Cms\Menu\Domain\Builder\Type\DefaultTypesRegistrator:
        tags: [ menu.builder.type_registrator ]

    Tulia\Cms\Menu\Domain\Builder\Identity\Providers\HomepageProvider:
        tags: [ menu.identity_provider ]
        bind:
            $homepage: 'homepage'

    Tulia\Cms\Menu\Domain\Builder\Identity\Providers\UrlProvider:
        tags: [ menu.identity_provider ]
