<?php

declare(strict_types=1);

namespace Tulia\Cms\Node\Query\Model;

use DateTime;
use Exception;
use InvalidArgumentException;
use Tulia\Cms\Metadata\MagickMetadataTrait;
use Tulia\Cms\Metadata\Metadata;
use Tulia\Cms\Metadata\MetadataTrait;

/**
 * @author Adam Banaszkiewicz
 */
class Node
{
    use MagickMetadataTrait;
    use MetadataTrait;

    protected $id;
    protected $type;
    protected $status;
    protected $websiteId;
    protected $publishedAt;
    protected $publishedTo;
    protected $createdAt;
    protected $updatedAt;
    protected $authorId;
    protected $parentId;
    protected $level;
    protected $category;
    protected $locale;
    protected $title;
    protected $slug;
    protected $introduction;
    protected $content;
    protected $contentSource;
    protected $visibility;
    protected $autogeneratedLocale;

    /**
     * @var string[]
     */
    protected static $fields = [
        'id'                  => 'id',
        'type'                => 'type',
        'status'              => 'status',
        'website_id'          => 'websiteId',
        'published_at'        => 'publishedAt',
        'published_to'        => 'publishedTo',
        'created_at'          => 'createdAt',
        'updated_at'          => 'updatedAt',
        'author_id'           => 'authorId',
        'parent_id'           => 'parentId',
        'level'               => 'level',
        'category'            => 'category',
        'locale'              => 'locale',
        'title'               => 'title',
        'slug'                => 'slug',
        'introduction'        => 'introduction',
        'content'             => 'content',
        'content_source'      => 'contentSource',
    ];

    /**
     * @param array $data
     *
     * @return Node
     *
     * @throws Exception
     */
    public static function buildFromArray(array $data): self
    {
        $node = new self();

        if (isset($data['id']) === false) {
            throw new InvalidArgumentException('Node ID must be provided.');
        }

        if (isset($data['website_id']) === false) {
            throw new InvalidArgumentException('Node website_id must be provided.');
        }

        if (isset($data['locale']) === false) {
            $data['locale'] = 'en_US';
        }

        $data = static::setDatetime($data, 'published_at', new DateTime());
        $data = static::setDatetime($data, 'published_to');
        $data = static::setDatetime($data, 'created_at', new DateTime());
        $data = static::setDatetime($data, 'updated_at');

        $node->setId($data['id']);
        $node->setType($data['type'] ?? 'page');
        $node->setStatus($data['status'] ?? 'published');
        $node->setWebsiteId($data['website_id']);
        $node->setPublishedAt($data['published_at']);
        $node->setPublishedTo($data['published_to']);
        $node->setCreatedAt($data['created_at']);
        $node->setUpdatedAt($data['updated_at']);
        $node->setAuthorId($data['author_id'] ?? null);
        $node->setParentId($data['parent_id'] ?? null);
        $node->setLevel((int) ($data['level'] ?? 0));
        $node->setCategory($data['category'] ?? null);
        $node->setLocale($data['locale']);
        $node->setTitle($data['title'] ?? '');
        $node->setSlug($data['slug'] ?? '');
        $node->setIntroduction($data['introduction'] ?? '');
        $node->setContent($data['content'] ?? '');
        $node->setContentSource($data['content_source'] ?? '');
        $node->setAutogeneratedLocale($data['autogenerated_locale'] ?? false);

        $node->setMetadata(new Metadata($data['metadata'] ?? []));

        return $node;
    }

    /**
     * {@inheritdoc}
     */
    private static function setDatetime(array $data, string $key, $default = null): array
    {
        if (\array_key_exists($key, $data) === false) {
            $data[$key] = $default;
        } elseif ($data[$key] === null && $default === null) {
            // Do nothing, allow to null;
        } elseif ($data[$key] instanceof DateTime === false) {
            $data[$key] = new DateTime($data[$key]);
        }

        return $data;
    }

    /**
     * {@inheritdoc}
     */
    public function toArray(array $params = []): array
    {
        $params = array_merge([
            'skip' => [],
        ], $params);

        $result = [];

        /*foreach ($this->getMetadata()->all() as $key => $val) {
            $result[$key] = $val;
        }*/

        foreach (static::$fields as $key => $property) {
            $result[$key] = $this->{$property};
        }

        foreach ($params['skip'] as $skip) {
            unset($result[$skip]);
        }

        return $result;
    }

    /**
     * {@inheritdoc}
     */
    public function hasId(): bool
    {
        return (bool) $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * {@inheritdoc}
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * {@inheritdoc}
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * {@inheritdoc}
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * {@inheritdoc}
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * {@inheritdoc}
     */
    public function getWebsiteId(): ?string
    {
        return $this->websiteId;
    }

    /**
     * {@inheritdoc}
     */
    public function setWebsiteId(?string $websiteId): void
    {
        $this->websiteId = $websiteId;
    }

    /**
     * {@inheritdoc}
     */
    public function getPublishedAt(): DateTime
    {
        return $this->publishedAt;
    }

    /**
     * {@inheritdoc}
     */
    public function setPublishedAt(DateTime $publishedAt): void
    {
        $this->publishedAt = $publishedAt;
    }

    /**
     * {@inheritdoc}
     */
    public function getPublishedTo(): ?DateTime
    {
        return $this->publishedTo;
    }

    /**
     * {@inheritdoc}
     */
    public function setPublishedTo(?DateTime $publishedTo): void
    {
        $this->publishedTo = $publishedTo;
    }

    /**
     * {@inheritdoc}
     */
    public function getCreatedAt(): DateTime
    {
        return $this->createdAt;
    }

    /**
     * {@inheritdoc}
     */
    public function setCreatedAt(DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * {@inheritdoc}
     */
    public function getUpdatedAt(): ?DateTime
    {
        return $this->updatedAt;
    }

    /**
     * {@inheritdoc}
     */
    public function setUpdatedAt(?DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthorId(): ?string
    {
        return $this->authorId;
    }

    /**
     * {@inheritdoc}
     */
    public function setAuthorId(?string $authorId): void
    {
        $this->authorId = $authorId;
    }

    /**
     * {@inheritdoc}
     */
    public function getParentId(): ?string
    {
        return $this->parentId;
    }

    /**
     * {@inheritdoc}
     */
    public function setParentId(?string $parentId): void
    {
        $this->parentId = $parentId;
    }

    /**
     * {@inheritdoc}
     */
    public function getLevel(): int
    {
        return $this->level;
    }

    /**
     * {@inheritdoc}
     */
    public function setLevel(int $level): void
    {
        $this->level = $level;
    }

    /**
     * {@inheritdoc}
     */
    public function getCategory(): ?string
    {
        return $this->category;
    }

    /**
     * {@inheritdoc}
     */
    public function setCategory(?string $category): void
    {
        $this->category = $category;
    }

    /**
     * {@inheritdoc}
     */
    public function getLocale(): ?string
    {
        return $this->locale;
    }

    /**
     * {@inheritdoc}
     */
    public function setLocale(?string $locale): void
    {
        $this->locale = $locale;
    }

    /**
     * {@inheritdoc}
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * {@inheritdoc}
     */
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    /**
     * {@inheritdoc}
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * {@inheritdoc}
     */
    public function setSlug(?string $slug): void
    {
        $this->slug = $slug;
    }

    /**
     * {@inheritdoc}
     */
    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    /**
     * {@inheritdoc}
     */
    public function setIntroduction(?string $introduction): void
    {
        $this->introduction = $introduction;
    }

    /**
     * {@inheritdoc}
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * {@inheritdoc}
     */
    public function setContent($content): void
    {
        $this->content = $content;
    }

    /**
     * {@inheritdoc}
     */
    public function getContentSource(): ?string
    {
        return $this->contentSource;
    }

    /**
     * {@inheritdoc}
     */
    public function setContentSource(?string $contentSource): void
    {
        $this->contentSource = $contentSource;
    }

    /**
     * {@inheritdoc}
     */
    public function getAutogeneratedLocale(): bool
    {
        return $this->autogeneratedLocale;
    }

    /**
     * {@inheritdoc}
     */
    public function setAutogeneratedLocale($autogeneratedLocale): void
    {
        $this->autogeneratedLocale = (bool) $autogeneratedLocale;
    }
}
