services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        Tulia\Cms\Filemanager\Application\Command\CommandInterface:
            tags: [ filemanager.command ]
        Tulia\Cms\Filemanager\Domain\ImageSize\ImagesSizeProviderInterface:
            tags: [ filemanager.image_size.provider ]

    Tulia\Cms\Filemanager\:
        resource: '../../../../**'
        exclude: '../../../../{Infrastructure/Framework/Resources,Domain/WriteModel/Model,Domain/ReadModel/Model}'

    Tulia\Cms\Filemanager\Application\Service\Cropper:
        bind:
            $filesDirectory: '%kernel.public_dir%'

    Tulia\Cms\Filemanager\Infrastructure\Framework\Twig\Extension\FilemanagerExtension:
        bind:
            $publicDir: '%kernel.public_dir%'

    Tulia\Cms\Filemanager\Domain\ImageSize\Registry:
        bind:
            $providers: !tagged_iterator filemanager.image_size.provider

    Tulia\Cms\Filemanager\Application\Command\CommandRegistry:
        bind:
            $commands: !tagged_iterator filemanager.command

    Tulia\Cms\Filemanager\Application\Command\Upload:
        bind:
            $projectDir: '%kernel.project_dir%'

    Tulia\Cms\Filemanager\Infrastructure\Framework\Theme\Customizer\FilepickerControl:
        tags: [ theme.customizer.control ]
