services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\SearchAnything\:
        resource: '../../../**'
        exclude:
            - '../../../Framework/Resources'
            - '../../../Model'

    Tulia\Cms\SearchAnything\SearchEngine\SearchEngineInterface:
        class: Tulia\Cms\SearchAnything\SearchEngine\SearchEngine
        bind:
            $providers: !tagged_iterator search.provider
