services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tulia\Cms\ContentBlock\:
        resource: '../../../../**'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/**'
