framework:
    public_paths:
        '%kernel.project_dir%/src/Cms/ContactForm/Infrastructure/Framework/Resources/public/dist': '/core/contact-forms'
    translator:
        paths:
            - '%kernel.project_dir%/src/Cms/ContactForm/Infrastructure/Framework/Resources/translations'
    templating:
        paths:
            - { name: cms/forms, path: '%kernel.project_dir%/src/Cms/ContactForm/Infrastructure/Framework/Resources/views/frontend' }
            - { name: backend/forms, path: '%kernel.project_dir%/src/Cms/ContactForm/Infrastructure/Framework/Resources/views/backend' }
    assetter:
        assets:
            tulia.contact_forms:
                scripts:
                    - /assets/core/contact-forms/js/build.js

cms:
    content_building:
        content_type_entry:
            contact_form:
                type: content_block
                name: Contact form
                icon: null
                controller: null
                is_routable: false
                is_hierarchical: false
                routing_strategy: null
                layout:
                    sections:
                        main:
                            groups:
                                fields_group:
                                    name: fields
                                    active: true
                                    order: 0
                                    fields:
                                        form_id:
                                            type: text
                                            name: Form to show
                                            is_multilingual: false
                                            configuration:
                                                - { code: icon, value: /assets/theme/tulia/lisa/images/content-block/icon/company-in-numbers.png }
                                            constraints:
                                                -
                                                    code: required
                                                -
                                                    code: length
                                                    modificators:
                                                        - { code: min, value: 0 }
                                                        - { code: max, value: 127 }
                                        text_field:
                                            type: text
                                            name: Text
                                            repeatable_for: repeatable_field_group
                                        filepicker:
                                            type: filepicker
                                            name: Filepicker
                                            repeatable_for: repeatable_field_group
                                        repeatable_field_group:
                                            type: repeatable
                                            name: Pole repeatable
                                            fields: [ text_field, filepicker ]
