services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        Tulia\Cms\ContactForm\Domain\FieldType\FieldTypeInterface:
            tags: [ cms.form.field_type ]
        Tulia\Cms\ContactForm\Domain\FieldType\FieldParserInterface:
            tags: [ cms.form.field_parser ]

    Tulia\Cms\ContactForm\:
        resource: '../../../../**'
        exclude:
            - '../../../../{Infrastructure/Framework/Resources,Domain/Event,Domain/Exception,Domain/FieldsParser/Exception,Domain/WriteModel/Model}'
            - '../../../../Domain/FieldsParser/DynamicShortcode.php'

    Tulia\Cms\ContactForm\Domain\FieldType\FieldsTypeRegistryInterface:
        class: Tulia\Cms\ContactForm\Domain\FieldType\FieldsTypeRegistry
        bind:
            $sourceTypes: !tagged_iterator cms.form.field_type
            $sourceParsers: !tagged_iterator cms.form.field_parser

    Tulia\Cms\ContactForm\Domain\SearchAnything\SearchProvider:
        tags:
            - { name: search.provider, priority: 600 }
