<?php

declare(strict_types=1);

namespace Tulia\Cms\Theme\Infrastructure\Framework\Theme\Customizer\Changeset;

use Tulia\Component\Theme\Customizer\Changeset\Changeset as BaseChangeset;

/**
 * @author Adam Banaszkiewicz
 */
class Changeset extends BaseChangeset implements ChangesetInterface
{
    /**
     * @var null|string
     */
    protected $authorId;

    /**
     * @var bool
     */
    protected $autogeneratedLocale;

    /**
     * @return null|string
     */
    public function getAuthorId(): ?string
    {
        return $this->authorId;
    }

    /**
     * @param null|string $authorId
     */
    public function setAuthorId(?string $authorId): void
    {
        $this->authorId = $authorId;
    }

    /**
     * @return bool
     */
    public function isAutogeneratedLocale(): bool
    {
        return $this->autogeneratedLocale;
    }

    /**
     * @param bool $autogeneratedLocale
     */
    public function setAutogeneratedLocale(bool $autogeneratedLocale): void
    {
        $this->autogeneratedLocale = $autogeneratedLocale;
    }
}
