{% assets ['content_builder.layout_builder.routable_content_type'] %}

{% trans_default_domain 'content_builder' %}

<div id="content-builder-routable-content-type-builder"></div>

<script nonce="{{ csp_nonce() }}">
    window.ContentBuilderLayoutBuilder = {
        translations: {
            pageTitle: '{{ pageTitle }}',
            yes: '{{ 'yes'|trans({}, 'messages') }}',
            no: '{{ 'no'|trans({}, 'messages') }}',
            close: '{{ 'close'|trans({}, 'messages') }}',
            cancel: '{{ 'cancel'|trans({}, 'messages') }}',
            create: '{{ 'create'|trans({}, 'messages') }}',
            icon: '{{ 'icon'|trans({}, 'messages') }}',
            save: '{{ 'save'|trans({}, 'messages') }}',
            publishedAt: '{{ 'publishedAt'|trans({}, 'messages') }}',
            publicationStatus: '{{ 'publicationStatus'|trans({}, 'messages') }}',
            author: '{{ 'author'|trans({}, 'messages') }}',
            flags: '{{ 'flags'|trans({}, 'node') }}',
            title: '{{ 'title'|trans({}, 'messages') }}',
            slug: '{{ 'slug'|trans({}, 'messages') }}',
            contentTypeName: '{{ 'contentTypeName'|trans }}',
            contentTypeNameInfo: '{{ 'contentTypeNameInfo'|trans }}',
            contentTypeCode: '{{ 'contentTypeCode'|trans }}',
            contentTypeCodeHelp: '{{ 'contentTypeCodeHelp'|trans }}',
            editContentTypeDetails: '{{ 'editContentTypeDetails'|trans }}',
            addNewSection: '{{ 'addNewSection'|trans }}',
            addNewField: '{{ 'addNewField'|trans }}',
            fieldLabel: '{{ 'fieldLabel'|trans }}',
            fieldLabelHelp: '{{ 'fieldLabelHelp'|trans }}',
            fieldId: '{{ 'fieldId'|trans }}',
            fieldIdHelp: '{{ 'fieldIdHelp'|trans }}',
            youCannotCreateTwoFieldsWithTheSameId: '{{ 'youCannotCreateTwoFieldsWithTheSameId'|trans }}',
            theseOptionsWillNotBeEditableAfterSave: '{{ 'theseOptionsWillNotBeEditableAfterSave'|trans }}',
            editField: '{{ 'editField'|trans }}',
            fieldType: '{{ 'fieldType'|trans }}',
            removeField: '{{ 'removeField'|trans }}',
            removeSection: '{{ 'removeSection'|trans }}',
            multilingualField: '{{ 'multilingualField'|trans }}',
            multilingualFieldInfo: '{{ 'multilingualFieldInfo'|trans }}',
            nextStep: '{{ 'nextStep'|trans }}',
            pleaseFillThisField: '{{ 'pleaseFillThisField'|trans }}',
            fieldCodeMustContainOnlyAlphanumsAndUnderline: '{{ 'fieldCodeMustContainOnlyAlphanumsAndUnderline'|trans }}',
            fieldTypeConfiguration: '{{ 'fieldTypeConfiguration'|trans }}',
            fieldDetails: '{{ 'fieldDetails'|trans }}',
            fieldTypeConstraints: '{{ 'fieldTypeConstraints'|trans }}',
            routableType: '{{ 'routableType'|trans }}',
            routableTypeHelp: '{{ 'routableTypeHelp'|trans }}',
            hierarchicalType: '{{ 'hierarchicalType'|trans }}',
            hierarchicalTypeHelp: '{{ 'hierarchicalTypeHelp'|trans }}',
            pleaseSelectValue: '{{ 'pleaseSelectValue'|trans }}',
            internalFields: '{{ 'internalFields'|trans }}',
            fieldHasErrors: '{{ 'fieldHasErrors'|trans }}',
            routingStrategy: '{{ 'routingStrategy'|trans }}',
            routingStrategyHelp: '{{ 'routingStrategyHelp'|trans }}',
        },
        fieldTypes: {{ fieldTypes|json_encode|raw }},
        routingStrategies: {{ routingStrategies|json_encode|raw }},
        model: {{ model|json_encode|raw }},
        errors: {{ errors|json_encode|raw }},
        multilingual: {{ multilingual ? 'true' : 'false' }},
        creationMode: {{ creationMode ? 'true' : 'false' }},
        listingUrl: '{{ path('backend.content_builder.homepage') }}',
        csrfToken: '{{ csrf_token('create-content-type') }}',
    };
</script>
