services:
    _defaults:
        autoconfigure: true
        autowire: true

    Tulia\Cms\BodyClass\:
        resource: '../../../../*'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/*'
            - '../../../../**/Model/*'
            - '../../../../**/Exception/*'

    Tulia\Cms\BodyClass\Domain\Service\BodyClassService:
        bind:
            $collectors: !tagged_iterator body_class.collector
