services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Theme\:
        resource: '../../../../*'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/*'
            - '../../../../**/Model/*'
            - '../../../../**/Exception/*'
            - '../../../../UI/Web/Controller/Backend/Theme.php'

    Tulia\Component\Theme\Loader\ThemeLoader\ThemeLoaderInterface:
        class: Tulia\Cms\Theme\Infrastructure\Framework\Theme\Loader\ThemeLoader

    Tulia\Component\Theme\Activator\ActivatorInterface:
        class: Tulia\Cms\Theme\Infrastructure\Framework\Theme\Activator\Activator
        bind:
            $configFilename: '%kernel.project_dir%/config/dynamic/themes.php'

    Tulia\Cms\Theme\Infrastructure\Cms\BackendMenu\AppearenceMenuBuilder:
        tags: [ backend_menu.builder ]

    Tulia\Cms\Theme\Infrastructure\Filemanager\ImageSize\ThemeConfigurationProvider:
        tags: [ filemanager.image_size.provider ]

    Tulia\Component\Theme\Customizer\Changeset\Storage\StorageInterface:
        class: Tulia\Cms\Theme\Infrastructure\Framework\Theme\Customizer\Changeset\Storage\DatabaseStorage

    Tulia\Component\Theme\Customizer\Changeset\Factory\ChangesetFactoryInterface:
        class: Tulia\Component\Theme\Customizer\Changeset\Factory\ChangesetFactory
        bind:
            $classname: \Tulia\Cms\Theme\Infrastructure\Framework\Theme\Customizer\Changeset\Changeset
