services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Theme\:
        resource: '../../../../*'
        exclude:
            - '../../../../UI/Web/Controller/Backend/Theme.php'

    Tulia\Component\Theme\Loader\ThemeLoader\ThemeLoaderInterface:
        class: Tulia\Cms\Theme\Infrastructure\Framework\Theme\Loader\ThemeLoader

    Tulia\Component\Theme\Activator\ActivatorInterface:
        class: Tulia\Cms\Theme\Infrastructure\Framework\Theme\Activator\Activator

    Tulia\Cms\Theme\Infrastructure\Cms\BackendMenu\AppearenceMenuBuilder:
        tags: [ backend_menu.builder ]
