backend.settings.send_test_email:
    path: /administrator/settings/-/send-test-email
    controller: Tulia\Cms\Settings\UserInterface\Web\Backend\Controller\Settings::sendTestEmail
    methods: POST|GET

backend.settings:
    path: /administrator/settings/{group}
    controller: Tulia\Cms\Settings\UserInterface\Web\Backend\Controller\Settings::show
    methods: GET|POST
    requirements:
        group: '[a-z0-9\._]+'
    defaults:
        group: null
