services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Settings\:
        resource: '../../../../**'
        exclude: '../../../../{Infrastructure/Framework/Resources}'

    Tulia\Cms\Settings\Ports\Domain\Group\SettingsGroupRegistryInterface:
        class: Tulia\Cms\Settings\Domain\Group\SettingsRegistryRegistry
        bind:
            $factories: !tagged_iterator settings.group_factory
            $groups: !tagged_iterator settings.group

    Tulia\Cms\Settings\Domain\SearchAnything\SearchProvider:
        tags:
            - { name: search.provider, priority: 600 }

    Tulia\Cms\Settings\UserInterface\Web\Backend\Settings\CmsSettingsGroup:
        tags:
            - { name: settings.group, priority: 1000 }
