services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Taxonomy\:
        resource: '../../../../*'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/*'
            - '../../../../**/Model/*'
            - '../../../../**/Exception/*'

    Tulia\Cms\Taxonomy\Domain\TaxonomyType\RegistryInterface:
        class: Tulia\Cms\Taxonomy\Domain\TaxonomyType\Registry
        bind:
            $registrators: !tagged_iterator taxonomy.type.registrator
            $storages: !tagged_iterator taxonomy.type.storage

    Tulia\Cms\Taxonomy\UserInterface\Web\Backend\Form\Extension\DefaultFieldsExtension:
        tags: [ form_extension ]

    Tulia\Cms\Taxonomy\UserInterface\Web\Backend\Form\Extension\TaxonomyTypeExtensionAggregate:
        tags: [ form_extension_aggregate ]

    Tulia\Cms\Taxonomy\Domain\Metadata\DefaultMetadataRegistrator:
        tags: [ metadata.registrator ]

    Tulia\Cms\Taxonomy\Infrastructure\Framework\Routing\Router:
        tags: [ routing_chain.router ]

    Tulia\Cms\Taxonomy\Domain\Routing\Strategy\TaxonomyRoutingStrategyRegistry:
        bind:
            $strategies: !tagged_iterator taxonomy.routing.strategy

    Tulia\Cms\Taxonomy\Domain\Menu\IdentityProvider:
        tags: [ menu.identity_provider ]
