services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Taxonomy\:
        resource: '../../../../**'
        exclude: '../../../../{Infrastructure/Framework/Resources}'

    Tulia\Cms\Taxonomy\Infrastructure\Framework\Routing\SymfonyRouter:
        tags: [ routing_chain.router ]

    Tulia\Cms\Taxonomy\Domain\Menu\IdentityProvider:
        tags: [ menu.identity_provider ]
