services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\BackendMenu\:
        resource: '../../../../*'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/*'
            - '../../../../**/Model/*'
            - '../../../../**/Exception/*'

    Tulia\Cms\BackendMenu\Domain\Builder\HtmlBuilderInterface:
        class: Tulia\Cms\BackendMenu\Domain\Builder\HtmlBuilder
        bind:
            $builders: !tagged_iterator backend_menu.builder
