services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\BackendMenu\:
        resource: '../../../../*'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/*'

    Tulia\Cms\BackendMenu\Application\HtmlBuilderInterface:
        class: Tulia\Cms\BackendMenu\Application\HtmlBuilder
        bind:
            $builders: !tagged_iterator backend_menu.builder
