<?php

declare(strict_types=1);

namespace Tulia\Cms\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * @author Adam Banaszkiewicz
 */
final class Version20210313083947 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        $this->addSql(<<<EOL
CREATE TABLE `#__customizer_changeset` (
  `id` varchar(36) COLLATE utf8_unicode_ci NOT NULL,
  `website_id` varchar(36) COLLATE utf8_unicode_ci NOT NULL,
  `theme` varchar(36) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(16) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `author_id` varchar(36) COLLATE utf8_unicode_ci DEFAULT NULL,
  `payload` json DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
EOL
);
        $this->addSql(<<<EOL
CREATE TABLE `#__customizer_changeset_lang` (
  `customizer_changeset_id` varchar(36) COLLATE utf8_unicode_ci NOT NULL,
  `locale` varchar(11) COLLATE utf8_unicode_ci NOT NULL,
  `autogenerated_locale` tinyint(3) UNSIGNED NOT NULL DEFAULT '1',
  `payload_localized` json DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
EOL
);
        $this->addSql(<<<EOL
ALTER TABLE `#__customizer_changeset`
  ADD PRIMARY KEY (`id`),
  ADD KEY `theme` (`website_id`,`type`,`theme`) USING BTREE;
EOL
);
        $this->addSql(<<<EOL
ALTER TABLE `#__customizer_changeset_lang`
  ADD UNIQUE KEY `customizer_changeset_id` (`customizer_changeset_id`,`locale`);
EOL
);
        $this->addSql(<<<EOL
ALTER TABLE `#__customizer_changeset`
  ADD CONSTRAINT `pk_customizer_changeset_website_id` FOREIGN KEY (`website_id`) REFERENCES `#__website` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
EOL
);
        $this->addSql(<<<EOL
ALTER TABLE `#__customizer_changeset_lang`
  ADD CONSTRAINT `customizer_changeset_lang_ibfk_1` FOREIGN KEY (`customizer_changeset_id`) REFERENCES `#__customizer_changeset` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
EOL
);
    }

    public function down(Schema $schema) : void
    {
        $this->addSql('DROP TABLE `#__customizer_changeset`');
        $this->addSql('DROP TABLE `#__customizer_changeset_lang`');
    }
}
