services:
    Tulia\Framework\Database\ConnectionInterface:
        class: Tulia\Framework\Database\Connection
        factory: Doctrine\DBAL\DriverManager::getConnection
        arguments:
            -
                dbname: '%env(string:DATABASE_NAME)%'
                user: '%env(string:DATABASE_USER)%'
                password: '%env(string:DATABASE_PASS)%'
                host: '%env(string:DATABASE_HOST)%'
                port: '%env(int:DATABASE_PORT)%'
                driver: '%env(string:DATABASE_TYPE)%'
                wrapperClass: Tulia\Framework\Database\Connection
                driverOptions:
                    1002: "SET NAMES 'UTF8'"

    Doctrine\DBAL\Connection: '@Tulia\Framework\Database\ConnectionInterface'
