services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Component\Security\Core\User\UserCheckerInterface:
        class: Symfony\Component\Security\Core\User\UserChecker

    Symfony\Component\Security\Core\User\UserProviderInterface:
        class: Symfony\Component\Security\Core\User\ChainUserProvider
        arguments:
            - !tagged_iterator security.user_provider
