services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Framework\Security\Http\ContentSecurityPolicy\ContentSecurityPolicyInterface:
        class: Tulia\Framework\Security\Http\ContentSecurityPolicy\ContentSecurityPolicy

    Tulia\Framework\Security\Http\ContentSecurityPolicy\EventListener\ResponseHeaderRegistrator:
        tags: [ kernel.event_subscriber ]

    Tulia\Framework\Twig\Extension\CspExtension:
        tags: [ twig.extension ]
