imports:
    - { resource: security.http.yaml }
    - { resource: security.http.csp.yaml }
    - { resource: security.http.firewall.yaml }
    - { resource: security.csrf.yaml }
    - { resource: security.core.user.yaml }
    - { resource: security.core.encoder.yaml }
    - { resource: security.core.authorisation.yaml }
    - { resource: security.core.authentication.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Framework\Security\:
        resource: '../../../Security/*'
        exclude:
            - '../../../Security/Http/Firewall/ContextListener.php'
            - '../../../Security/Http/Firewall/BackendAccess.php'
