services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface:
        class: Symfony\Component\Security\Core\Encoder\EncoderFactory
        arguments:
            -
                Symfony\Component\Security\Core\User\User:
                    algorithm: auto
                    class: Symfony\Component\Security\Core\Encoder\NativePasswordEncoder
                    arguments: []
                    hash_algorithm: native
