services:
    _defaults:
        autowire: true
        autoconfigure: true

    Twig\Environment:
        factory: [ Tulia\Framework\Twig\Factory, factory ]
        bind:
            $debug: '%kernel.environment%'

    Twig\Loader\LoaderInterface:
        class: Twig\Loader\ChainLoader

    Twig\RuntimeLoader\RuntimeLoaderInterface:
        class: Twig\RuntimeLoader\ContainerRuntimeLoader

    Twig\Profiler\Profile: ~

    Tulia\Component\Templating\Twig\Loader\LazyArrayLoader:
        tags: [ twig.loader ]
        bind:
            $templates: '%framework.twig.loader.array.templates%'

    Twig\Loader\FilesystemLoader:
        tags: [ twig.loader ]
        factory: [ Tulia\Component\Templating\Twig\Loader\FilesystemLoaderFactory, factory ]
        bind:
            $paths: '%framework.twig.loader.filesystem.paths%'

    Tulia\Component\Templating\Twig\Loader\AdvancedFilesystemLoader:
        tags: [ twig.loader ]
        factory: [ Tulia\Framework\Twig\Loader\AdvancedFilesystemLoaderFactory, factory ]
        bind:
            $paths: '%framework.templating.paths%'

    Symfony\Bridge\Twig\DataCollector\TwigDataCollector:
        tags: [ profiler.data_collector ]

    Twig\Extension\StringLoaderExtension:
        tags: [ twig.extension ]
