services:
    Symfony\Component\HttpFoundation\RequestStack: ~

    request_stack: '@Symfony\Component\HttpFoundation\RequestStack'

    Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestAttributeValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 100 }

    Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    Symfony\Component\HttpKernel\Controller\ArgumentResolver\SessionValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver:
        class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
        arguments:
            - '@Psr\Container\ContainerInterface'
        tags:
            - { name: controller.argument_value_resolver, priority: -50 }

    Symfony\Component\HttpKernel\Controller\ArgumentResolver\DefaultValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: -100 }

    Symfony\Component\HttpKernel\Controller\ArgumentResolver\VariadicValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: -150 }
