framework:
    assetter:
        assets:
            datatables_core:
                scripts: [ '/assets/core/datatables/datatables.min.js' ]
                styles: [ '/assets/core/datatables/datatables.min.css' ]
                priority: 800
            datatables:
                scripts: [ '/assets/core/datatables/integrations/js/dataTables.bootstrap4.min.js' ]
                styles: [ '/assets/core/datatables/integrations/css/dataTables.bootstrap4.min.css' ]
                require: [ 'datatables_core' ]
                priority: 500
            datatable_tulia:
                scripts: [ '/assets/core/datatable-tulia/datatable.js' ]
                require: [ 'datatables' ]
                priority: 200
            backend.font:
                styles: [ 'https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext' ]
                group: head
            backend.theme.head:
                styles: [ '/assets/core/backend/theme/css/backend-theme.css' ]
                require: [ 'backend.font', 'animate_css' ]
                group: head
            backend.theme:
                scripts: [ '/assets/core/backend/theme/js/backend-theme.bundle.min.js' ]
                require: [ 'vue', 'simplebar', 'lodash', 'backend.theme.head' ]
            backend:
                require: [ 'bootstrap', 'font_awesome', 'chosen', 'sweetalert2', 'js_cookie', 'backend.theme' ]
            customizer.back:
                scripts: [ '/assets/core/customizer/backend/customizer.js' ]
                styles: [ '/assets/core/customizer/backend/customizer.css' ]
                require: [ 'bootstrap', 'font_awesome', 'chosen', 'sweetalert2' ]
            customizer.front:
                scripts: [ '/assets/core/customizer/frontend/customizer.js' ]
            frontend:
                styles: [ '/assets/core/frontend/default-assets/style.css' ]
                priority: 1000
                group: head
            tulia_dynamic_form:
                scripts: [ '/assets/core/tulia-dynamic-form/tulia-dynamic-form.js' ]
                collection: tulia-dynamic-form
                priority: 1000
                group: head
