framework:
    assetter:
        assets:
            jquery:
                scripts: [ '/assets/core/jquery/jquery-3.4.1.min.js' ]
                group: head
                priority: 1000
            jquery_ui:
                scripts: [ /assets/core/jquery-ui/js/jquery-ui.min.js ]
                styles: [ /assets/core/jquery-ui/css/jquery-ui.min.css ]
                group: head
                priority: 500
            popperjs:
                scripts: [ '/assets/core/popperjs/popper.min.js' ]
                priority: 800
            font_awesome:
                styles: [ '/assets/core/font-awesome/css/all.min.css' ]
                priority: 1000
                group: head
            animate_css:
                styles: [ '/assets/core/animate-css/animate.min.css' ]
                priority: 1000
            lodash:
                priority: 1000
                scripts: [ '/assets/core/lodash/lodash.min.js' ]
            chosen:
                require: [ 'chosen.css', 'chosen.js' ]
            chosen.css:
                styles: [ '/assets/core/chosen/chosen.min.css' ]
                priority: 500
                group: head
            chosen.js:
                scripts: [ '/assets/core/chosen/chosen.jquery.min.js' ]
                priority: 500
            sweetalert2:
                scripts: [ '/assets/core/sweetalert2/sweetalert2.min.js' ]
                priority: 500
            js_cookie:
                scripts: [ '/assets/core/js-cookie/js.cookie-2.2.0.min.js' ]
                priority: 500
            simplebar:
                scripts: [ '/assets/core/simplebar/simplebar.min.js' ]
                styles: [ '/assets/core/simplebar/simplebar.min.css' ]
                priority: 500
            datetimepicker:
                scripts: [ '/assets/core/bootstrap-datetimepicker/js/tempusdominus-bootstrap-4.min.js', '/assets/core/bootstrap-datetimepicker-custom/defaults.js' ]
                styles: [ '/assets/core/bootstrap-datetimepicker/css/tempusdominus-bootstrap-4.min.css' ]
                require: [ 'momentjs' ]
                priority: 500
            momentjs:
                scripts: [ '/assets/core/momentjs/moment-with-locales.min.js' ]
                priority: 800
            vue:
                scripts: [ '/assets/core/vuejs/vue.min.js' ]
                priority: 500
            nestable:
                scripts: [ '/assets/core/jquery-nestable/jquery.nestable.min.js' ]
                styles: [ '/assets/core/jquery-nestable/jquery.nestable.min.css' ]
                priority: 500
            datatables_core:
                scripts: [ '/assets/core/datatables/datatables.min.js' ]
                styles: [ '/assets/core/datatables/datatables.min.css' ]
                priority: 800
            datatables:
                scripts: [ '/assets/core/datatables/integrations/js/dataTables.bootstrap4.min.js' ]
                styles: [ '/assets/core/datatables/integrations/css/dataTables.bootstrap4.min.css' ]
                require: [ 'datatables_core' ]
                priority: 500
            datatable_tulia:
                scripts: [ '/assets/core/datatable-tulia/datatable.js' ]
                require: [ 'datatables' ]
                priority: 200
            jquery_typeahead:
                scripts: [ '/assets/core/jquery-typeahead/jquery.typeahead.min.js' ]
                styles: [ '/assets/core/jquery-typeahead/jquery.typeahead.min.css' ]
                priority: 500
            bootstrap:
                require: [ 'jquery', 'popperjs', 'bootstrap.css', 'bootstrap.js' ]
            bootstrap.css:
                styles: [ '/assets/core/bootstrap/css/bootstrap.min.css' ]
                priority: 500
                group: head
            bootstrap.js:
                scripts: [ '/assets/core/bootstrap/js/bootstrap.min.js' ]
                priority: 500
            jstree:
                scripts: [ '/assets/core/jstree/jstree.min.js' ]
                styles: [ '/assets/core/jstree/themes/default/style.min.css' ]
                priority: 500
            fileapi:
                scripts: [ '/assets/core/fileapi/FileAPI.html5.min.js' ]
                priority: 500
                group: head
            masonry:
                scripts: [ '/assets/core/masonry/masonry.pkgd.min.js' ]
                priority: 500
                group: head
            backend.font:
                styles: [ 'https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext' ]
                group: head
            backend.theme.head:
                styles: [ '/assets/core/backend/theme/css/style.css' ]
                require: [ 'backend.font', 'animate_css' ]
                group: head
            backend.theme:
                scripts: [ '/assets/core/backend/theme/js/bundle.min.js' ]
                require: [ 'vue', 'simplebar', 'lodash', 'backend.theme.head' ]
            backend:
                scripts: [ '/assets/core/backend/selected-elements-actions.js' ]
                styles: [ '/assets/core/backend/bootstrap-translations.css' ]
                require: [ 'bootstrap', 'font_awesome', 'chosen', 'sweetalert2', 'js_cookie', 'backend.theme' ]
            customizer.back:
                scripts: [ '/assets/core/backend/customizer/customizer.js' ]
                styles: [ '/assets/core/backend/customizer/customizer.css' ]
                require: [ 'bootstrap', 'font_awesome', 'chosen', 'sweetalert2' ]
            customizer.front:
                scripts: [ '/assets/core/frontend/customizer/customizer.js' ]
            frontend:
                styles: [ '/assets/core/frontend/default-assets/style.css' ]
                priority: 1000
                group: head
            filemanager:
                styles: [ '/assets/core/filemanager/css/filemanager.css' ]
                scripts:
                    - '/assets/core/filemanager/js/src/variables.js'
                    - '/assets/core/filemanager/js/src/front-controller.js'
                    - '/assets/core/filemanager/js/src/command-bus.js'
                    - '/assets/core/filemanager/js/src/container.js'
                    - '/assets/core/filemanager/js/src/directory-tree.js'
                    - '/assets/core/filemanager/js/src/event-dispatcher.js'
                    - '/assets/core/filemanager/js/src/files-collection.js'
                    - '/assets/core/filemanager/js/src/manager.js'
                    - '/assets/core/filemanager/js/src/model.js'
                    - '/assets/core/filemanager/js/src/selection.js'
                    - '/assets/core/filemanager/js/src/view.js'
                    - '/assets/core/filemanager/js/src/cache.js'
                    - '/assets/core/filemanager/js/src/upload.js'
                    - '/assets/core/filemanager/js/src/config.js'
                require: [ 'jquery', 'jstree', 'fileapi' ]
                group: head
            tulia-editor:
                styles: [ '/assets/core/tulia-editor/css/tulia-editor.min.css' ]
                scripts: [ '/assets/core/tulia-editor/js/tulia-editor.min.js', '/assets/core/tulia-editor/js/tulia-editor.run.js' ]
                group: head
