imports:
    - { resource: assets.yaml }

framework:
    templating:
        namespace_overwrite:
            - { from: '@parent/', to: '@theme/' }
            - { from: '@cms/',    to: '@parent/overwrite/cms/' }
            - { from: '@module/', to: '@parent/overwrite/module/' }
            - { from: '@widget/', to: '@parent/overwrite/widget/' }
