imports:
    - { resource: services/routing.yaml }
    - { resource: services/utils.yaml }
    - { resource: services/metadata.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $publicDir: '%kernel.public_dir%'
            $rootDir: '%kernel.project_dir%'
            $assetsPublicPaths: '%framework.assets.public_paths%'

    Tulia\Cms\Platform\:
        resource: '../../../../*'
        exclude:
            - '../../../../**/Resources/**'
            - '../../../../**/Domain/**'
            - '../../../../**/Model/**'
            - '../../../../**/*Exception.php'
            - '../../../../**/*Trait.php'
            - '../../../../**/*View.php'
            - '../../../../**/*Response.php'
            - '../../../../**/*Event.php'

    Tulia\Cms\Platform\UserInterface\Console\Command\AssetsPublish:
        tags:
            - { name: console.command, command: 'assets:publish' }

    Tulia\Cms\Platform\Infrastructure\Framework\Theme\Storage\DirectoryDiscoveryStorage:
        bind:
            $extensionsDirectory: '%kernel.project_dir%/extension/theme'

    Tulia\Component\Theme\Storage\StorageInterface: '@Tulia\Cms\Platform\Infrastructure\Framework\Theme\Storage\DirectoryDiscoveryStorage'
